# Generated by Django 3.2.7 on 2021-10-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('housing_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Town_House', 'Town House')], max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('admin_check', models.BooleanField(default=False)),
                ('amenities', models.ManyToManyField(blank=True, to='app.Amenitie')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField(blank=True)),
                ('beds', models.IntegerField(blank=True)),
                ('baths', models.IntegerField(blank=True)),
                ('rent', models.IntegerField(blank=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housing')),
            ],
        ),
    ]
