# Generated by Django 3.2.7 on 2021-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
