# Generated by Django 3.2.7 on 2021-10-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_housing_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='rent',
        ),
    ]
